### PR TITLE
Expose Markdown extensions features

### PR DESCRIPTION
**Pull request by iptux**
the base project [hoemark][] have some extension flag to support extra markdown syntax, but this feature is ignored in anddown, so I expose this feature to app

[hoemark]: https://github.com/hoedown/hoedown

### CODE REVIEW

**Comment by jffrymrtn** [comment]
Wow, giving this a try. Thanks a lot! This looks immensely great

**Comment by jffrymrtn** [comment]
@iptux Just finished testing and reviewing this code. Quick question: What does the flag (none, basic, advanced) do? Can we just use advanced markdown rendering by default (and remove the preference to choose)?

**Comment by jffrymrtn** [comment]
@iptux nvm, read through the source of hoedown. Pretty cool stuff! I think I'll make some mods to hide the preference and choose a default extension (advance)

**Comment by iptux** [comment]
I am also thinking about the preference, which may make user confusing. The mods will make user easier. :+1:

**Pull request merged**
