### PR TITLE
Further changes to the ListView UI

### PR DESCRIPTION
**Pull request by Minty123**
Another slight change, tell me what you think about it! :-)

I saw in issue #45 that you already made changes to the ListView UI but I think it could be improved even further.

I did the following:
-> Made it compacter (changed title font style and size). It's in a way inspired by Google Drive ListView.
-> Made subtitle a little bit darker and thus more readable
-> Added a round background to the file/folder icon with different colors for file and folder (Maybe that helps a bit with #46?)
-> Darkened the secondary color a tone down

Screenshots for comparison: (Left is new, right is old)
screenshot_2015-01-22-09-57-08

### CODE REVIEW

**Comment by jffrymrtn** [comment]
Looks cool! I like the more compactness without making it too thing.

Main concern: the circled file/folder icons look too similar to the action
button. Although I do also want to make folders vs files more obvious...

Here's one of my ideas I've been toying around with:

I've been looking at Drive as an example too and what they do is separate
them with a list view header (eg. "Folders"). I may just do that instead of
color changes since colors would also be delicate with themes.

Another:

Add an arrow to the right of each list view item for folders to indicate it
has children. Not so much a fan of this one though...

**Comment by Minty123** [comment]
Thanks for the response!

I decided to go for the circle icons because I saw them in various apps and thought it looked pretty good. I understand your concerns though that's why I thought about using headers at first too.

For now, I'll revert the icons and keep the rest. Is that ok with you, @jffrymrtn?

**Comment by jffrymrtn** [comment]
@Minty123 Sounds good!

Which apps did you see uses them btw? I'll take a look too -- reviewing a bunch of options right now. Might still go back to circles! Though I'm worried users might be confused between the FAB and the circles. Not ruling it out though

**Comment by Minty123** [comment]
I got the main idea from [Amaze File Manager](https://play.google.com/store/apps/details?id=com.amaze.filemanager). I also took a look at the Lollipop contacts app and [Jair Player](https://play.google.com/store/apps/details?id=aj.jair.music) (see third screenshot)

**Comment by jffrymrtn** [comment]
@Minty123 Ahhh, interesting thanks, I'll take a look! First glance looks like they use them as buttons (for ActionMode) which would make sense

**Comment by Minty123** [comment]
@jffrymrtn Icons are back to normal now. 
screenshot_2015-01-22-15-20-07

**Comment by patcon** [comment]
Also, quick note, mostly informed by my reading "information dashboard design" (ie. not totally pulled from my ass). (Note: not a designer, but worked in design-focused dev shop where lots of convos rub off)

The thought was that by adding color to the icons, it makes the UI yell "FOLDERS AND FILES" louder than it yells the name of the file itself. When you're skimming a long list of files, the name is where you want attention drawn, not the icon for the filetype, which is kinda secondary. So yeah, my $0.02 is that big circled color icons are distracting considering how the diff between files/folders just needs a small visual hint that can be observed easily :)

**Pull request merged**
