### PR TITLE
Removed local copy of anddown

### PR DESCRIPTION
**Pull request by plafue**
I'm opening a pull request, as pushing this just like that may be a bit too harsh.
I'm not sure if there is any reason at all to have the anddown sources in this repo, maybe i'm making a mistake (?). Resolving the dependency though gradle worked flawlessly.

Please test before merging!

### CODE REVIEW

**Comment by iptux** [comment]
upstream [anddown][] don't have extra markdown syntax support, see https://github.com/commonsguy/cwac-anddown/pull/8

[anddown]: https://github.com/commonsguy/cwac-anddown

**Comment by plafue** [comment]
@jffrymrtn thanks for merging! 
@iptux the merge does deactivate the extensions, is this a problem? 
// Disable emphasis_between_words(bit 11)
// Require a space after '#' in headers(bit 12)
// Instead of guessing by context, parse $inline math$ and $$always block math$$(bit 13)
// Don't parse indented code blocks(bit 14)
Are these extensions critical?

**Comment by jffrymrtn** [comment]
ah, seems like bit 11 is critical.

**Comment by jffrymrtn** [comment]
ah, seems like bit 11 is critical.

**Comment by plafue** [comment]
Is it? Maybe we should clarify which Markdown standard is supported by the app. That would really help me moving forward.

**Pull request merged**
