### PR TITLE
Added ViewSwitcher, circularRevealAnimation. Fixed FAB menu titles

### LINKED ISSUE #152: FAB offset by 16dp on Marshmallow
The third party library used for FAB offsets the button on the right by a 16dp margin on Marshmallow devices. This can be rectified either by 

1. Switching to a new third party library 
2. Or by modifying the existing code to remove the right margin. 
3. Using the `android.support.design.FloatingActionButton` which will take care of padding for all Android versions.

### PR DESCRIPTION
**Pull request by aharish**
Added a `ViewSwitcher` to switch the `EditText` in the `Toolbar` to a `TextView` that matches the Material Design guidelines of a `Toolbar` title. Also, attached a `OnFocusChangeListener` to the `EditText` to listen to the focus state of the `EditText` when the user clicks on the `HighlightingEditor` below.  

Created a circular reveal animation while the Breadcrumb `View` is made visible. Haven't added an animation while setting the `Visibility` to `GONE` yet. This only works on API 21 & above.

Changed the `EditText` layout in the `CreateFolderDialog` to match Material Design guidelines. 

Added the missing style required to view the `FloatingActionMenu`'s titles. 

Removed `paddingLeft` and `paddingRight` in the `EditText` in `toolbar_note.xml` and instead added `contentInsetStart` to the 72dp base gridline as per Material Design specifications.

Commit [60abad8](https://github.com/aharish/writeily-pro/commit/60abad8ccff3d5888099e4b8045c92763eb29325) fixes #152. This commit also adds a very rudimentary system to hide the FAB as per the design guidelines on scroll down. While it does work, I have used an `AbsListView.OnScrollListener` to check when the `ListView` is being scrolled. The hiding feels a bit delayed. Perhaps a better implementation can be done with `MotionEvent`? I will take a look into this later on. I have also made the FABs secondary icons to be a bit smaller as per design guidelines. This also required a change in icons from the Google Icon Library (size 24dp). This commit also fixes a couple of niggles with the `EditText` in the create dialog folder and fixes the breadcrumbs issue before the animation started playing. 

Check the commit below for the code changes! :)

### CODE REVIEW

**Comment by aharish** [comment]
Is there any reason for this not getting merged?

**Comment by aharish** [comment]
I'm closing this pull request as it's been over nine months with no apparent interest from the project maintainer. For anyone interested in the changes, they can find them on my fork.

**Comment by gsantner** [comment]
@aharish Hi there, as the project is no longer maintained/dead, and not available on F-Droid too anymore, I wanted to keep it alive. For that I forked and made it compile and runable again with current sdk and appcompat. I also cherry-picked your commits of this PR. I don't know yet where it will lead, and how much time I can invest, but I want to at least keep it updated to latest Android SDK.

This is my repository: <https://github.com/gsantner/marowni>

**Comment by aharish** [comment]
@gsantner Hello there! Thanks for forking it to keep the project alive. I'm happy to help with the project if you need any help. :)

**Comment by gsantner** [comment]
@aharish:
Any help very welcome! You can also visit our chat channels if you want to know some more where to start then in README

Basically theres not really much a single line of Writeily leftover, everything reworked and modernized :D

**Pull request closed without merging**
