### PR TITLE
Multiple changes to the settings screens

### PR DESCRIPTION
**Pull request by Minty123**
-> Moved strings that don't have to be translated (like version number, names, etc)
-> Redesigned the about screen layout
-> Settings screens are now affected by the selected theme
-> Reformatted and rearranged code

### CODE REVIEW

**Comment by jffrymrtn** [comment]
You're very good at creating very efficient code! Nice PR!

**Comment by Minty123** [comment]
Thanks! :-) Before I create a new issue: Do you know why the action bar is missing in the about screen? I tried to get it back but I couldn't get it to work yet...

**Comment by jffrymrtn** [comment]
It's because the PreferenceScreen isn't abiding by any theme (which is fine). I don't think a Toolbar is needed there, anyway, I think

**Comment by Minty123** [comment]
I don't know if you got my message. I replied to the notification email directly. I'll just post it again here.

--------------------


have to disagree on that. The action bar - in my opinion - is an important part of Android design language. It tells me what screen I'm on and that I can go back from there via that backwards arrow. That's the case at least for the main PreferenceScreen.

Other than that, I think it looks weird for it to be there on the main PreferenceScreen but not on the about screen.

Just my two cents here. :-)

**Comment by jffrymrtn** [comment]
Good point about the back arrow actually. I'll look into getting the toolbar in the About screen. I'll get it fixed :) thanks for the reminder about the back arrow!

**Pull request merged**
